baseurl = "/"
languageCode = "en-us"
title = "Pulum Anda Ltd"

[params]
  description = "Using [Victor Hugo] theme"

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 1
[[menu.main]]
    name = "Properties"
    url  = "/properties"
    weight = 2
[[menu.main]]
    name = "Image Gallery"
    url  = "/gallery"
    weight = 3

